version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: pg_demo
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5433"
  liquibase:
    image: liquibase/liquibase:4.27.0
    depends_on:
      - postgres
    volumes:
      - ./:/liquibase/changelog
    command: >
      --defaultsFile=/liquibase/changelog/liquibase.properties update