name: Database Migration

on:
  push:
    branches: [ main ]

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: demo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install Liquibase
        run: |
          curl -LO https://github.com/liquibase/liquibase/releases/download/v4.27.0/liquibase-4.27.0.tar.gz
          tar -xzf liquibase-4.27.0.tar.gz
          chmod +x liquibase

      - name: Run Migration
        run: |
          ./liquibase \
            --url=jdbc:postgresql://postgres:5432/demo \
            --username=postgres \
            --password=123456 \
            --changeLogFile=db/changelog.sql \
            update